-- MySQL Script generated by MySQL Workbench
-- Thu May 14 17:38:01 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema deca_19L4_MP_06
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema deca_19L4_MP_06
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `deca_19L4_MP_06` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema deca_19l4_mp_06
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema deca_19l4_mp_06
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `deca_19l4_mp_06` DEFAULT CHARACTER SET utf8 ;
USE `deca_19L4_MP_06` ;

-- -----------------------------------------------------
-- Table `deca_19L4_MP_06`.`04_familias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deca_19L4_MP_06`.`04_familias` (
  `idfamilia` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfamilia`),
  UNIQUE INDEX `idfamilia_UNIQUE` (`idfamilia` ASC) VISIBLE,
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deca_19L4_MP_06`.`04_mariachis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deca_19L4_MP_06`.`04_mariachis` (
  `idmariachis` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `alcunha` VARCHAR(45) NOT NULL,
  `familia_idfamilia` INT NOT NULL,
  PRIMARY KEY (`idmariachis`),
  INDEX `fk_mariachis_familia1_idx` (`familia_idfamilia` ASC) VISIBLE,
  UNIQUE INDEX `idmariachis_UNIQUE` (`idmariachis` ASC) VISIBLE,
  CONSTRAINT `fk_mariachis_familia1`
    FOREIGN KEY (`familia_idfamilia`)
    REFERENCES `deca_19L4_MP_06`.`04_familias` (`idfamilia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deca_19L4_MP_06`.`04_sombreros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deca_19L4_MP_06`.`04_sombreros` (
  `idsombreros` INT NOT NULL,
  `premio` VARCHAR(45) NULL,
  `mariachis_idmariachis` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idsombreros`),
  UNIQUE INDEX `idsombreros_UNIQUE` (`idsombreros` ASC) VISIBLE,
  INDEX `fk_sombreros_mariachis_idx` (`mariachis_idmariachis` ASC) VISIBLE,
  CONSTRAINT `fk_sombreros_mariachis`
    FOREIGN KEY (`mariachis_idmariachis`)
    REFERENCES `deca_19L4_MP_06`.`04_mariachis` (`idmariachis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deca_19L4_MP_06`.`04_cidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deca_19L4_MP_06`.`04_cidades` (
  `idcidades` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcidades`),
  UNIQUE INDEX `idcidades_UNIQUE` (`idcidades` ASC) VISIBLE,
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `deca_19L4_MP_06`.`04_chicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deca_19L4_MP_06`.`04_chicas` (
  `idchicas` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `data_nascimento` DATE NULL,
  `cidades_idcidades` INT NOT NULL,
  `chica_idchicas` INT NULL,
  PRIMARY KEY (`idchicas`),
  UNIQUE INDEX `idchicas_UNIQUE` (`idchicas` ASC) VISIBLE,
  INDEX `fk_chicas_cidades1_idx` (`cidades_idcidades` ASC) VISIBLE,
  INDEX `fk_chicas_chicas1_idx` (`chica_idchicas` ASC) VISIBLE,
  CONSTRAINT `fk_chicas_cidades1`
    FOREIGN KEY (`cidades_idcidades`)
    REFERENCES `deca_19L4_MP_06`.`04_cidades` (`idcidades`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_chicas_chicas1`
    FOREIGN KEY (`chica_idchicas`)
    REFERENCES `deca_19L4_MP_06`.`04_chicas` (`idchicas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deca_19L4_MP_06`.`04_mariachis_has_chicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deca_19L4_MP_06`.`04_mariachis_has_chicas` (
  `mariachis_idmariachis` INT NOT NULL,
  `chicas_idchicas` INT NOT NULL,
  `data_inicio` DATE NULL,
  `data_fim` DATE NULL,
  PRIMARY KEY (`mariachis_idmariachis`, `chicas_idchicas`),
  INDEX `fk_mariachis_has_chicas_chicas1_idx` (`chicas_idchicas` ASC) VISIBLE,
  UNIQUE INDEX `mariachis_idmariachis_UNIQUE` (`mariachis_idmariachis` ASC) VISIBLE,
  CONSTRAINT `fk_mariachis_has_chicas_mariachis1`
    FOREIGN KEY (`mariachis_idmariachis`)
    REFERENCES `deca_19L4_MP_06`.`04_mariachis` (`idmariachis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mariachis_has_chicas_chicas1`
    FOREIGN KEY (`chicas_idchicas`)
    REFERENCES `deca_19L4_MP_06`.`04_chicas` (`idchicas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deca_19L4_MP_06`.`mp_ambiente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deca_19L4_MP_06`.`mp_ambiente` (
  `idmp_ambiente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `obs` VARCHAR(100) NULL,
  PRIMARY KEY (`idmp_ambiente`),
  UNIQUE INDEX `idmp_ambiente_UNIQUE` (`idmp_ambiente` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deca_19L4_MP_06`.`mp_ano`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deca_19L4_MP_06`.`mp_ano` (
  `idmp_ano` INT NOT NULL AUTO_INCREMENT,
  `ano` DATE NOT NULL,
  PRIMARY KEY (`idmp_ano`),
  UNIQUE INDEX `idmp_ano_UNIQUE` (`idmp_ano` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deca_19L4_MP_06`.`mp_autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deca_19L4_MP_06`.`mp_autores` (
  `idmp_autores` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmp_autores`),
  UNIQUE INDEX `idmp_autores_UNIQUE` (`idmp_autores` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deca_19L4_MP_06`.`mp_tema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deca_19L4_MP_06`.`mp_tema` (
  `idmp_tema` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmp_tema`),
  UNIQUE INDEX `idtema_UNIQUE` (`idmp_tema` ASC) VISIBLE,
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deca_19L4_MP_06`.`mp_livros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deca_19L4_MP_06`.`mp_livros` (
  `idmp_livros` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `capa` VARCHAR(200) NOT NULL,
  `sinopse` VARCHAR(45) NOT NULL,
  `review` VARCHAR(45) NULL,
  `data_edicao` DATE NULL,
  `data_lancamento` DATE NULL,
  `mp_ambiente_idmp_ambiente` INT NOT NULL,
  `mp_ano_idmp_ano` INT NOT NULL,
  `mp_ano_ano` DATE NOT NULL,
  `mp_autores_idmp_autores` INT NOT NULL,
  `tema_idtema` INT NOT NULL,
  PRIMARY KEY (`idmp_livros`),
  UNIQUE INDEX `idmp_livros_UNIQUE` (`idmp_livros` ASC) VISIBLE,
  INDEX `fk_mp_livros_mp_ambiente1_idx` (`mp_ambiente_idmp_ambiente` ASC) VISIBLE,
  INDEX `fk_mp_livros_mp_ano1_idx` (`mp_ano_idmp_ano` ASC, `mp_ano_ano` ASC) VISIBLE,
  INDEX `fk_mp_livros_mp_autores1_idx` (`mp_autores_idmp_autores` ASC) VISIBLE,
  INDEX `fk_mp_livros_tema1_idx` (`tema_idtema` ASC) VISIBLE,
  CONSTRAINT `fk_mp_livros_mp_ambiente1`
    FOREIGN KEY (`mp_ambiente_idmp_ambiente`)
    REFERENCES `deca_19L4_MP_06`.`mp_ambiente` (`idmp_ambiente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mp_livros_mp_ano1`
    FOREIGN KEY (`mp_ano_idmp_ano` , `mp_ano_ano`)
    REFERENCES `deca_19L4_MP_06`.`mp_ano` (`idmp_ano` , `ano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mp_livros_mp_autores1`
    FOREIGN KEY (`mp_autores_idmp_autores`)
    REFERENCES `deca_19L4_MP_06`.`mp_autores` (`idmp_autores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mp_livros_tema1`
    FOREIGN KEY (`tema_idtema`)
    REFERENCES `deca_19L4_MP_06`.`mp_tema` (`idmp_tema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deca_19L4_MP_06`.`mp_leitores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deca_19L4_MP_06`.`mp_leitores` (
  `idmp_leitores` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idmp_leitores`),
  UNIQUE INDEX `idleitores_UNIQUE` (`idmp_leitores` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `password_UNIQUE` (`password` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `deca_19L4_MP_06`.`mp_livros_has_leitores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deca_19L4_MP_06`.`mp_livros_has_leitores` (
  `mp_livros_idmp_livros` INT NOT NULL,
  `leitores_idleitores` INT NOT NULL,
  PRIMARY KEY (`mp_livros_idmp_livros`, `leitores_idleitores`),
  INDEX `fk_mp_livros_has_leitores_leitores1_idx` (`leitores_idleitores` ASC) VISIBLE,
  INDEX `fk_mp_livros_has_leitores_mp_livros1_idx` (`mp_livros_idmp_livros` ASC) VISIBLE,
  CONSTRAINT `fk_mp_livros_has_leitores_mp_livros1`
    FOREIGN KEY (`mp_livros_idmp_livros`)
    REFERENCES `deca_19L4_MP_06`.`mp_livros` (`idmp_livros`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_mp_livros_has_leitores_leitores1`
    FOREIGN KEY (`leitores_idleitores`)
    REFERENCES `deca_19L4_MP_06`.`mp_leitores` (`idmp_leitores`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `deca_19l4_mp_06` ;

-- -----------------------------------------------------
-- Table `deca_19l4_mp_06`.`ambiente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deca_19l4_mp_06`.`ambiente` (
  `idambiente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `observaçoes` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idambiente`),
  UNIQUE INDEX `idambiente_UNIQUE` (`idambiente` ASC) VISIBLE,
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `deca_19l4_mp_06`.`autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deca_19l4_mp_06`.`autores` (
  `idautores` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idautores`),
  UNIQUE INDEX `idautores_UNIQUE` (`idautores` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `deca_19l4_mp_06`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deca_19l4_mp_06`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategoria`),
  UNIQUE INDEX `idcategoria_UNIQUE` (`idcategoria` ASC) VISIBLE,
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 14
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `deca_19l4_mp_06`.`leitores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deca_19l4_mp_06`.`leitores` (
  `idleitores` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password_hash` VARCHAR(256) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`idleitores`),
  UNIQUE INDEX `idleitores_UNIQUE` (`idleitores` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `deca_19l4_mp_06`.`editora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deca_19l4_mp_06`.`editora` (
  `ideditora` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ideditora`),
  UNIQUE INDEX `ideditora_UNIQUE` (`ideditora` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `deca_19l4_mp_06`.`livros2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deca_19l4_mp_06`.`livros2` (
  `idlivro` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `data_lancamento` YEAR NULL DEFAULT NULL,
  `data_edicao` YEAR NOT NULL,
  `sinopse` MEDIUMTEXT NOT NULL,
  `review` MEDIUMTEXT NULL DEFAULT NULL,
  `categoria_id` INT NOT NULL,
  `autor_id` INT NOT NULL,
  `editora_id` INT NOT NULL,
  `ambiente_id` INT NOT NULL,
  `capa` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idlivro`),
  INDEX `editora_id_fk` (`idlivro` ASC) VISIBLE,
  INDEX `autor_id_fk` (`idlivro` ASC) VISIBLE,
  INDEX `categoria_id_fk` USING BTREE (`idlivro`) VISIBLE,
  INDEX `ambiente_id_fk` (`idlivro` ASC) VISIBLE,
  INDEX `autor_id` (`autor_id` ASC) VISIBLE,
  INDEX `editora_id` (`editora_id` ASC) VISIBLE,
  INDEX `categoria_id` (`categoria_id` ASC) VISIBLE,
  INDEX `ambiente_id` (`ambiente_id` ASC) VISIBLE,
  CONSTRAINT `ambiente_id`
    FOREIGN KEY (`ambiente_id`)
    REFERENCES `deca_19l4_mp_06`.`ambiente` (`idambiente`),
  CONSTRAINT `autor_id`
    FOREIGN KEY (`autor_id`)
    REFERENCES `deca_19l4_mp_06`.`autores` (`idautores`),
  CONSTRAINT `categoria_id`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `deca_19l4_mp_06`.`categoria` (`idcategoria`),
  CONSTRAINT `editora_id`
    FOREIGN KEY (`editora_id`)
    REFERENCES `deca_19l4_mp_06`.`editora` (`ideditora`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `deca_19l4_mp_06`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deca_19l4_mp_06`.`comentarios` (
  `idcomentarios` INT NOT NULL AUTO_INCREMENT,
  `texto_comentario` VARCHAR(255) NOT NULL,
  `ref_id_livro` INT NOT NULL,
  `ref_id_leitores` INT NOT NULL,
  PRIMARY KEY (`idcomentarios`),
  INDEX `id_leitores` (`ref_id_leitores` ASC) VISIBLE,
  INDEX `ref_livro` (`ref_id_livro` ASC) VISIBLE,
  CONSTRAINT `id_leitores`
    FOREIGN KEY (`ref_id_leitores`)
    REFERENCES `deca_19l4_mp_06`.`leitores` (`idleitores`),
  CONSTRAINT `ref_livro`
    FOREIGN KEY (`ref_id_livro`)
    REFERENCES `deca_19l4_mp_06`.`livros2` (`idlivro`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `deca_19l4_mp_06`.`livros_has_leitores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `deca_19l4_mp_06`.`livros_has_leitores` (
  `livros_idlivros` INT NOT NULL,
  `leitores_idleitores` INT NOT NULL,
  PRIMARY KEY (`livros_idlivros`, `leitores_idleitores`),
  INDEX `fk_livros_has_leitores_leitores1_idx` (`leitores_idleitores` ASC) VISIBLE,
  INDEX `fk_livros_has_leitores_livros1_idx` (`livros_idlivros` ASC) VISIBLE,
  CONSTRAINT `fk_livros_has_leitores_leitores1`
    FOREIGN KEY (`leitores_idleitores`)
    REFERENCES `deca_19l4_mp_06`.`leitores` (`idleitores`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_livros_has_leitores_livros1`
    FOREIGN KEY (`livros_idlivros`)
    REFERENCES `deca_19l4_mp_06`.`livros2` (`idlivro`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
